CREATE DATABASE STUDY_CARS;
CREATE TABLE `COMPANY_NAME` (
	`COMPANY_NAME_ID`	VARCHAR(50)	NOT NULL,
	`COMPANY_NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `CAR_NAME` (
	`CAR_NAME_ID`	VARCHAR(50)	NOT NULL,
	`CAR_NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `CAR_YEAR` (
	`CAR_YEAR_ID`	VARCHAR(50)	NOT NULL,
	`CAR_YEAR`	VARCHAR(255)	NULL
);

CREATE TABLE `CAR_OPTIONS` (
	`OPTIONS_ID`	VARCHAR(50)	NOT NULL,
	`OPTIONS`	VARCHAR(255)	NULL
);

CREATE TABLE `CARS_INFORMATIONS_TOTAL` (
	`CARS_INFORMATIONS_TOTAL_ID`	VARCHAR(50)	NOT NULL,
	`COMPANY_NAME_ID`	VARCHAR(50)	NOT NULL,
	`OPTIONS_ID`	VARCHAR(50)	NOT NULL,
	`CAR_NAME_ID`	VARCHAR(50)	NOT NULL,
	`CAR_YEAR_ID`	VARCHAR(50)	NOT NULL
);

ALTER TABLE `COMPANY_NAME` ADD CONSTRAINT `PK_COMPANY_NAME` PRIMARY KEY (
	`COMPANY_NAME_ID`
);

ALTER TABLE `CAR_NAME` ADD CONSTRAINT `PK_CAR_NAME` PRIMARY KEY (
	`CAR_NAME_ID`
);

ALTER TABLE `CAR_YEAR` ADD CONSTRAINT `PK_CAR_YEAR` PRIMARY KEY (
	`CAR_YEAR_ID`
);

ALTER TABLE `CAR_OPTIONS` ADD CONSTRAINT `PK_CAR_OPTIONS` PRIMARY KEY (
	`OPTIONS_ID`
);

ALTER TABLE `CARS_INFORMATIONS_TOTAL` ADD CONSTRAINT `PK_CARS_INFORMATIONS_TOTAL` PRIMARY KEY (
	`CARS_INFORMATIONS_TOTAL_ID`,
	`COMPANY_NAME_ID`,
	`OPTIONS_ID`,
	`CAR_NAME_ID`,
	`CAR_YEAR_ID`
);

ALTER TABLE `CARS_INFORMATIONS_TOTAL` ADD CONSTRAINT `FK_COMPANY_NAME_TO_CARS_INFORMATIONS_TOTAL_1` FOREIGN KEY (
	`COMPANY_NAME_ID`
)
REFERENCES `COMPANY_NAME` (
	`COMPANY_NAME_ID`
);

ALTER TABLE `CARS_INFORMATIONS_TOTAL` ADD CONSTRAINT `FK_CAR_OPTIONS_TO_CARS_INFORMATIONS_TOTAL_1` FOREIGN KEY (
	`OPTIONS_ID`
)
REFERENCES `CAR_OPTIONS` (
	`OPTIONS_ID`
);

ALTER TABLE `CARS_INFORMATIONS_TOTAL` ADD CONSTRAINT `FK_CAR_NAME_TO_CARS_INFORMATIONS_TOTAL_1` FOREIGN KEY (
	`CAR_NAME_ID`
)
REFERENCES `CAR_NAME` (
	`CAR_NAME_ID`
);

ALTER TABLE `CARS_INFORMATIONS_TOTAL` ADD CONSTRAINT `FK_CAR_YEAR_TO_CARS_INFORMATIONS_TOTAL_1` FOREIGN KEY (
	`CAR_YEAR_ID`
)
REFERENCES `CAR_YEAR` (
	`CAR_YEAR_ID`
);

