CREATE DATABASE STUDY_USERS;
CREATE TABLE `SEX` (
	`SEX_ID`	VARCHAR(50)	NOT NULL,
	`SEX`	VARCHAR(255)	NULL
);

CREATE TABLE `D_ADDRESS` (
	`D_ADDRESS_ID`	VARCHAR(50)	NOT NULL,
	`D_ADDRESS`	VARCHAR(255)	NULL
);

CREATE TABLE `USER_INFORMATION` (
	`USER_INFORMATION_ID`	VARCHAR(50)	NOT NULL,
	`SEX_ID2`	VARCHAR(50)	NOT NULL,
	`D_ADDRESS_ID`	VARCHAR(50)	NOT NULL,
	`HOBBY_ID`	VARCHAR(50)	NOT NULL,
	`NAME`	VARCHAR(255)	NULL,
	`AGE`	VARCHAR(255)	NULL,
	`PHONE_NUMBER`	VARCHAR(255)	NULL,
	`EMAIL`	VARCHAR(255)	NULL
);

CREATE TABLE `HOBBY` (
	`HOBBY_ID`	VARCHAR(50)	NOT NULL,
	`HOBBY`	VARCHAR(255)	NULL
);

ALTER TABLE `SEX` ADD CONSTRAINT `PK_SEX` PRIMARY KEY (
	`SEX_ID`
);

ALTER TABLE `D_ADDRESS` ADD CONSTRAINT `PK_D_ADDRESS` PRIMARY KEY (
	`D_ADDRESS_ID`
);

ALTER TABLE `USER_INFORMATION` ADD CONSTRAINT `PK_USER_INFORMATION` PRIMARY KEY (
	`USER_INFORMATION_ID`,
	`SEX_ID2`,
	`D_ADDRESS_ID`,
	`HOBBY_ID`
);

ALTER TABLE `HOBBY` ADD CONSTRAINT `PK_HOBBY` PRIMARY KEY (
	`HOBBY_ID`
);

ALTER TABLE `USER_INFORMATION` ADD CONSTRAINT `FK_SEX_TO_USER_INFORMATION_1` FOREIGN KEY (
	`SEX_ID2`
)
REFERENCES `SEX` (
	`SEX_ID`
);

ALTER TABLE `USER_INFORMATION` ADD CONSTRAINT `FK_D_ADDRESS_TO_USER_INFORMATION_1` FOREIGN KEY (
	`D_ADDRESS_ID`
)
REFERENCES `D_ADDRESS` (
	`D_ADDRESS_ID`
);

ALTER TABLE `USER_INFORMATION` ADD CONSTRAINT `FK_HOBBY_TO_USER_INFORMATION_1` FOREIGN KEY (
	`HOBBY_ID`
)
REFERENCES `HOBBY` (
	`HOBBY_ID`
);

