CREATE DATABASE STUDY_MOVIES;
CREATE TABLE `MOVIE_NAME` (
	`MOVIE_NAME_ID`	VARCHAR(50)	NOT NULL,
	`MOVIE_NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `REVIEW_INFO` (
	`REVIEW_TITLE_ID`	VARCHAR(50)	NOT NULL,
	`REVIEW_TITLE`	VARCHAR(255)	NULL,
	`REVIEW_CONTENTS`	VARCHAR(255)	NULL
);

CREATE TABLE `REVIEW_DATE` (
	`REVIEW_DATE_ID`	VARCHAR(50)	NOT NULL,
	`REVIEW_DATE`	VARCHAR(255)	NULL
);

CREATE TABLE `REVIEW_RATING` (
	`REVIEW_RATING_ID`	VARCHAR(50)	NOT NULL,
	`REVIEW_RATING`	VARCHAR(255)	NULL
);

CREATE TABLE `REVIEW_WRITER` (
	`REVIEW_WRITER_ID`	VARCHAR(50)	NOT NULL,
	`REVIEW_WRITER`	VARCHAR(255)	NULL
);

CREATE TABLE `MOVIE_REVIEW_INFO` (
	`MOVIE_REVIEW_INFO`	VARCHAR(50)	NOT NULL,
	`REVIEW_TITLE_ID`	VARCHAR(50)	NOT NULL,
	`MOVIE_NAME_ID`	VARCHAR(50)	NOT NULL,
	`REVIEW_WRITER_ID`	VARCHAR(50)	NOT NULL,
	`REVIEW_DATE_ID`	VARCHAR(50)	NOT NULL,
	`REVIEW_RATING_ID`	VARCHAR(50)	NOT NULL
);

ALTER TABLE `MOVIE_NAME` ADD CONSTRAINT `PK_MOVIE_NAME` PRIMARY KEY (
	`MOVIE_NAME_ID`
);

ALTER TABLE `REVIEW_INFO` ADD CONSTRAINT `PK_REVIEW_INFO` PRIMARY KEY (
	`REVIEW_TITLE_ID`
);

ALTER TABLE `REVIEW_DATE` ADD CONSTRAINT `PK_REVIEW_DATE` PRIMARY KEY (
	`REVIEW_DATE_ID`
);

ALTER TABLE `REVIEW_RATING` ADD CONSTRAINT `PK_REVIEW_RATING` PRIMARY KEY (
	`REVIEW_RATING_ID`
);

ALTER TABLE `REVIEW_WRITER` ADD CONSTRAINT `PK_REVIEW_WRITER` PRIMARY KEY (
	`REVIEW_WRITER_ID`
);

ALTER TABLE `MOVIE_REVIEW_INFO` ADD CONSTRAINT `PK_MOVIE_REVIEW_INFO` PRIMARY KEY (
	`MOVIE_REVIEW_INFO`,
	`REVIEW_TITLE_ID`,
	`MOVIE_NAME_ID`,
	`REVIEW_WRITER_ID`,
	`REVIEW_DATE_ID`,
	`REVIEW_RATING_ID`
);

ALTER TABLE `MOVIE_REVIEW_INFO` ADD CONSTRAINT `FK_REVIEW_INFO_TO_MOVIE_REVIEW_INFO_1` FOREIGN KEY (
	`REVIEW_TITLE_ID`
)
REFERENCES `REVIEW_INFO` (
	`REVIEW_TITLE_ID`
);

ALTER TABLE `MOVIE_REVIEW_INFO` ADD CONSTRAINT `FK_MOVIE_NAME_TO_MOVIE_REVIEW_INFO_1` FOREIGN KEY (
	`MOVIE_NAME_ID`
)
REFERENCES `MOVIE_NAME` (
	`MOVIE_NAME_ID`
);

ALTER TABLE `MOVIE_REVIEW_INFO` ADD CONSTRAINT `FK_REVIEW_WRITER_TO_MOVIE_REVIEW_INFO_1` FOREIGN KEY (
	`REVIEW_WRITER_ID`
)
REFERENCES `REVIEW_WRITER` (
	`REVIEW_WRITER_ID`
);

ALTER TABLE `MOVIE_REVIEW_INFO` ADD CONSTRAINT `FK_REVIEW_DATE_TO_MOVIE_REVIEW_INFO_1` FOREIGN KEY (
	`REVIEW_DATE_ID`
)
REFERENCES `REVIEW_DATE` (
	`REVIEW_DATE_ID`
);

ALTER TABLE `MOVIE_REVIEW_INFO` ADD CONSTRAINT `FK_REVIEW_RATING_TO_MOVIE_REVIEW_INFO_1` FOREIGN KEY (
	`REVIEW_RATING_ID`
)
REFERENCES `REVIEW_RATING` (
	`REVIEW_RATING_ID`
);

