-- DELETE FROM table_name WHERE condition;

DELETE FROM VISITOR
WHERE VISITOR_ID = 'VISITE_11';

-- PARENT KEY 알고 있을 때
DELETE FROM VISITOR
WHERE NOTICE_ID = 'NOTICE_05'; 

DELETE FROM NOTICE
WHERE NOTICE_ID = 'NOTICE_05';

-- ** DELETE
-- Error Code: 1451. Cannot delete or update a parent row: a foreign key constraint fails (`STUDY_NOTICES`.`VISITOR`, CONSTRAINT `FK_NOTICE_TO_VISITOR_1` FOREIGN KEY (`NOTICE_ID`) REFERENCES `NOTICE` (`NOTICE_ID`))
